### ISSUE TITLE
Openning GLTF models in Sample Project

### ISSUE THREAD

**Issue by smtabatabaie** [KhronosGroup/UnityGLTF#163]
Hi, I'm trying to explore the sample project. I could load sample models in scene "TestSceneScene" in Unity 5.6 and could see the models. However I tried to put my own exported gltf models in the same folder and load them by changing the path in GLTFComponent script. But every time it gives me the error : 

> 404 - http://localhost:8080/TestScene/myModel.gltf
> UnityEngine.Debug:LogErrorFormat(String, Object[])
> UnityGLTF.Loader.<CreateHTTPRequest>c__Iterator1:MoveNext() (at Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs:48)
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 

and also this error : 

> Exception: Response code invalid
> UnityGLTF.Loader.WebRequestLoader+<CreateHTTPRequest>c__Iterator1.MoveNext () (at Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs:49)
> UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

I'll appreciate if someone can help me with this.
Thanks

**Comment by tufeixp** [comment]
anyone knows why?

**Comment by vicung** [comment]
Hello, sorry for pushing this old issue, but I have the exact same errors and couldn't find any solution for it. 

I'm totally new to glTF and after a little bit of trouble building/compiling the visual studio project I finally managed to get it done, but now when playing the example scenes I also get the 404 and Exception error. At first there was also a "Starting web server..." message but after copying the models  to the www folder (and commenting out one line of code, which did nothing) like this thread suggested https://github.com/KhronosGroup/UnityGLTF/issues/162 the message disappeared, but I still can't see any models just the floor plane and those two error messages remained.

Now I'm wondering if it's trying to start or reach a web server and if the problem might have to do with me being required to work behind a proxy from my company. I have already set the HTTPS_PROXY and HTTP_PROXY as system environment variables in Windows and want to know if UnityGLTF needs any further special settings?

**Comment by kenbier** [comment]
Confirming this error in 2018. The resolution posted in issue #162 worked for me though.
See the steps [here](https://github.com/KhronosGroup/UnityGLTF/issues/162#issuecomment-389386395)

**Comment by Arlorean** [comment]
I get this with Unity 2018.2.4f1 and even 5.6.5f1, but it was nothing to do with the Unity version for me.

It was because I had downloaded the [First built unity package release of UnityGLTF](https://github.com/KhronosGroup/UnityGLTF/releases/tag/v1.0.0) **UnityGLTF.unitypackage** (804 Kb) which comes with the Example **.unity** scenes but not the **www** folder that is needed at the same level as the **Assets** folder.

Downloading the [UnityGLTF-master.zip](https://github.com/KhronosGroup/UnityGLTF/archive/master.zip) of the project and copying the **www** directory into my local Unity project directory fixed the problem, as shown here:

![image](https://user-images.githubusercontent.com/1547800/50638529-fe06b500-0f55-11e9-81a6-2b11935db38a.png)

Hopefully this helps others who get the same ```Exception: Response code invalid error.``` message.

**Comment by rianders** [comment]
I got this error with the current released version. Will there be a new one without this issue?
