### ISSUE TITLE
Dirty frames are getting introduced in animation - animation looks messed up

### ISSUE THREAD

**Issue by ravip** [KhronosGroup/UnityGLTF#194]
Dirty frames are getting introduced in animation - animation looks messed up

Below is the gltf model which was tested on babylon js sandbox and loaded using UnityGLTF plugin from Unity editor. Animations were rendered properly on babylon sandbox however dirty frames got introduced when played using UnityGLTF plugin from Unity editor. (For Example: Play and observe frames form 0 to 2000 on Babylon sandbox and UNityGLTF plugin on Unity editor)

**Bablylon Sandbox:**
https://sandbox.babylonjs.com/

**GLTF Model:**
[ge_gltf.zip](https://github.com/KhronosGroup/UnityGLTF/files/2149132/ge_gltf.zip)

**Comment by ravip** [comment]
@blgrossMS 
Dear Sir,

Unity GLTF plugin is very good. I appreciate all the efforts put in.

However its not usable in real environment because Animations are not playing properly and has above bug. Earlier we had integrated this plugin however because of animation issue looks like it unusable. 

Could you please look into this?

Thanks in advance.

**Comment by blgrossMS** [comment]
I'll take a look over the next week

**Comment by ravip** [comment]
Thanks for taking this as priority @blgrossMS 

Here is the one more model for testing purpose. Try this with plugin as well as with babylon sandbox (Just drag drop the files to babylon sandbox to run it)

**Cutter 3D model:**
[cutter_gltf.zip](https://github.com/KhronosGroup/UnityGLTF/files/2158296/cutter_gltf.zip)

**Comment by supriyarasal** [comment]
Hi @blgrossMS ,
I am also facing same issue as @ravip mentioned for the 3d animation with UnityGLTF plugin on Unity editor .Please provide solution for the same.

Thanks .

**Comment by blgrossMS** [comment]
Update: still looking into it. I think the bug probably lies within the relationship between parent and children nodes.

**Comment by supriyarasal** [comment]
Thanks @blgrossMS ,
When you will release the fix for this issue?

**Comment by Amobiliya** [comment]
Hi @blgrossMS ,

I am facing the same issue.
While importing the scene from GLTFSceneimporter I am getting three types of animation clips i.e. separate for position, rotation and scale. And these clips are playing irrespective of each other means in my original animation rotation, position and scaling happened at the same time on the same click but here it behaves each partwise.

so, As per my understanding and observations instead of creating separate animations clip in (GLTFSceneImporter.cs ->Animation region) we need only one clip with all properties.

Thanks.

**Comment by shekhar331** [comment]
@blgrossMS 
Hello Sir, 
I am facing the same issue. The animations seem to work completely fine with simple animations (Single transform animation), but when several transforms are being  controlled the animation adds more keys (Dirty) into the animation clip. This part is crucial for the project. Can you please take a look into it and help out?

Thank  you.

**Comment by chakitp** [comment]
Hi All,
I was also facing same issue.
It was due to invalid quaternion interpolation.

![curve](https://user-images.githubusercontent.com/42670215/44705034-130c9c80-aabb-11e8-9413-65d3a2d9bb91.png)

I fixed it in  **UnityGLTF/UnityGLTF/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs** in **ConstructClip** Method.
[Reference](https://answers.unity.com/questions/253837/can-i-set-an-animationcurve-keyframes-interpolatio.html)

You can find it in below link.
[Dirty Animation Fix](https://github.com/chakitp/UnityGLTF/tree/chakitp-patch-for-Dirty-Animation)

**Comment by ericob** [comment]
Looks like this will be fixed in #234

**Comment by AdamMitchell-ms** [comment]
This now loads and animates smoothly.
