### ISSUE TITLE
Loading without Blocking

### ISSUE THREAD

**Issue by cwfitzgerald** [KhronosGroup/UnityGLTF#216]
I am attempting to write a GLTF-based world viewer with incremental loading. The assets are fairly large, so the GLTF models have to be added every time we want to load a new tile of the world. The issue we are currently having is that loading with GLTF blocks the main thread for about 500ms (loading 200K tri meshes). Unfortunately, even with the multithreading flag set to on, it doesn't help the large amount of blocking that happens. Is there any established way to deal with long periods of blocking? 

My current way for loading is to create a game object with a new GLTF component for each tile, adding and removing game objects as needed.

**Comment by blgrossMS** [comment]
Hi @cwfitzgerald,

The main problem is that before 2018.1/2 all Unity operations had to happen on the main thread. This has changed a bit with their job system which should allow us to multithread more parts of our load.

Historically to account for this problem we yield between major operations today (mesh load, texture load, material load etc).

One problem with runtime loading today is that all textures have to load on main thread (which can take on the magnitude of 100's of ms depending on type of device and size of texture) since glTF supports non GPU compressed textures as part of the main specification.

Depending on your application you can pack into your assets GPU packed textures as an extension and use that to improve your loading time.

We have an issue #9 which addresses the problem we have with texture load perf. @JohnCopicMS I believe is actively looking into this problem.

Creation of the Unity mesh also happens on the main thread. If the mesh creation is taking a while, we could take a PR which breaks the mesh load into segments (by splitting the mesh). 

However, I think the best solution to the problem is going to be a refactor which takes adantage of Unity's job system to parallelize and background thread the creation of the Unity objects. 

I might also recommend that you try using a LOD system to reduce the complexity of the initial models you are loading and load in the more complex models later. Take a look at the msft_lod extension: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/MSFT_lod 

Hope this helps! If you do end up working on this problem at all, feel free to post and ask questions 😄

**Comment by Zichuan-Wang** [comment]
Hi there, I made a PR #221 that added multithreading support to the importer. Please check it out! @cwfitzgerald @blgrossMS
