### ISSUE TITLE
Add support for animating blend shapes

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/UnityGLTF#482]
Blend shapes are populated correctly from glTF today, but animations targeting the weights are not.

**Comment by EricBeetsOfficial-Opuscope** [comment]
Hi there,
Is there any updates about it ?
It seems the `ouput` from `samplerCache.Output.AccessorContent` (in GLTFSceneInporter.cs : `ConstructClip` function ) contains null elements instead of having the morph animated values.
Do we have to search around the GLTFSerialization project ?

Thank in advance, 
Regards

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!

**Comment by EfimBash** [comment]
After loading a Glb model, the BlendShapes are present but do not animate as expected if given values. In Editor works fine

**Comment by hybridherbst** [comment]
@EfimBash if you have a specific model that reproduces the problem, please open a [new issue](https://github.com/KhronosGroup/UnityGLTF/issues/new) instead of adding information here. Thanks!
