### ISSUE TITLE
Exported GLB is very shiny

### ISSUE THREAD

**Issue by AytoMaximo** [KhronosGroup/UnityGLTF#546]
Hello!
I'm using Diffuse/Normal/Metallic/Roughness setup and get a very unexpected result after converting:

Original in Unity:
![image](https://user-images.githubusercontent.com/14392087/71976336-1bd0bf00-3227-11ea-9c4c-ec08289f81a7.png)

Output:
![image](https://user-images.githubusercontent.com/14392087/71976356-28edae00-3227-11ea-83d8-c3c68f84ba50.png)

It's a chair, but the top part looks like a metal.

**Comment by prajwalshettydev** [comment]
This happens because the "_Glossiness" field is misleading in the shader GLTFUtility/Standard(Mettalic) "Standard-Metallic" the _Glossiness actually represents _Roughness and hence 1-x negation is no longer required. Until the developer comes with the fix you can go file GLTFMaterial.cs and in CreateMaterial function, u can temporarily remove the 1-roughnessFactor for _glossiness and set it to just roughnessFactor

**Comment by AytoMaximo** [comment]
> This happens because the "_Glossiness" field is misleading in the shader GLTFUtility/Standard(Mettalic) "Standard-Metallic" the _Glossiness actually represents _Roughness and hence 1-x negation is no longer required. Until the developer comes with the fix you can go file GLTFMaterial.cs and in CreateMaterial function, u can temporarily remove the 1-roughnessFactor for _glossiness and set it to just roughnessFactor

Thank you for the answer! Unfortunately, I can't find CreateMaterial function in GLTFMaterial.cs. 
Variable "roughnessFactor" located in glTFPbrMetallicRoughness class there, but there is no some kind of  "1-roughnessFactor" step.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
