### ISSUE TITLE
gltf loads large models very slowly

### ISSUE THREAD

**Issue by foreverliu** [KhronosGroup/UnityGLTF#572]
gltf is very slow to load large models, an 80M file takes an hour to load.Can this be solved?

**Comment by javagl** [comment]
glTF is only a file/data format. How long it takes to load a model is (not really, but somewhat) independent of that. More precisely: glTF is designed so that it can be "loaded" quickly. The issue is therefore most likely related to the engine/renderer that you are using. 

So **where** and **how** are you "loading" the model? (And are you sure that it's not only due to a slow network connection, for example?)

**Comment by foreverliu** [comment]
[Uploading test.zip…]()
The model is gltf generated by sketchup conversion, and the loading speed is very slow. I load it locally.

**Comment by foreverliu** [comment]
Link: https://pan.baidu.com/s/1DX0EVc5HZbKkP-JyngfIEg Extraction     code: 6uax

**Comment by javagl** [comment]
> I load it locally.

In three.js, in Babylon.js, or in any other viewer? 

<sub>(Besides: I don't know which button to click for the download...)</sub>

**Comment by foreverliu** [comment]
it's loaded in Unity

**Comment by maybeTomorrow** [comment]
same to me . 40MB model cost 2 miniutes
