### ISSUE TITLE
 Problem in importing a glb file on runtime while playing apk file on Oculus Quest

### ISSUE THREAD

**Issue by waseemkhan1989** [KhronosGroup/UnityGLTF#613]
Hi,

I downloaded and imported the unity package of UnityGLTF in my project and I just added prefabs from one of given example scenes into my scene i.e.  GLTF (GLTFComponent script attached) and Server(WebServerComponent attached). 

![Image1](https://user-images.githubusercontent.com/25552247/96171416-2a21d900-0f25-11eb-824e-b304cace7133.png)

I build and run the apk file on Quest and I do not see any 3D object. The android catlog shows the following error:

![Capture2](https://user-images.githubusercontent.com/25552247/96171771-b0d6b600-0f25-11eb-9039-b34412bac7e0.PNG)

On unity editor,  it is working fine but on Android, I have to do some work. As I am new in this area, could someone please mention step by step procedure to import a glb file into scene from a server?

**Comment by waseemkhan1989** [comment]
Any help in this regard @robertlong @blgrossMS @stevenvergenz @AdamMitchell-ms ?

**Comment by paolis92** [comment]
Hi,
based on your error, your problem is here in WebServerComponent.Start() :
```
var appPath = Application.dataPath;
var wwwPath = appPath.Substring(0, appPath.LastIndexOf("Assets")) + "www";
```
In the editor it works because Application.dataPath returns the path of the project as mentioned here https://docs.unity3d.com/ScriptReference/Application-dataPath.html
Unity Editor: <path to project folder>/Assets
so here the Assets folder exists.

On Android it returns the path the apk or obb folder which does not contains Assets folder.
I guess that example works only in the editor because of that.

**Comment by waseemkhan1989** [comment]
@paolis92  thanks for reply! Yes you are right. Somehow I need to use "PersistentDataPath" and I tried this with other importers and they are working on Android. But I do not know  where I have to make modifications in this library for it to able to work.

**Comment by tamizhuser** [comment]
@waseemkhan1989 are you found the solution?. Please help me.
Thanks.
