### ISSUE TITLE
Building for Mac?

### ISSUE THREAD

**Issue by zynga-jpetersen** [KhronosGroup/UnityGLTF#77]
I realize this project is pre-1.0 so you may not be expecting people to be trying to build it, but I tried anyway.

I tried the steps described in the readme:
Open GLTFSerialization\GLTFSerialization.sln and compile for release. This will put the binaries in UnityGLTF\Assets\UnityGLTF\Plugins

From within both Rider and Monodevelop without success.

In monodevelop I get a project error with GLTFSerialization "Unknown ToolsVersion 15.0" and GLTFSerializationUWP failed to load.

In Rider GLTFSerializationUWP failed to load.
MSBuild targets were not found: Make sure that all SDKs required for projects in this solution are installed, or specify a different MSBuild version in settings.

Just a heads up since I'm guessing you have larger fish to fry.

Thanks.

**Comment by MSblgross** [comment]
We have not tested the project yet for OSX. I'm not quite sure what the restrictions would be. I'm guessing the project will need to be built with one of the Unity 3.5 .net configuration instead of .NET 3.5. The tools version 15.0 is referring to the latest MSBuild version which is coupled with VS 2017. I'm not familiar enough building on OSX to know about VS solution compatibility with other IDE's

Compiling on Windows to generate a dll that works with OSX may work, this would probably require this version of JSON.net https://github.com/SaladLab/Json.Net.Unity3D  

We want to make sure as many platforms work as possible, feel free to contribute back a OSX fix if you do figure out a solution. I'll be sure to add this to the backlog though.

**Comment by aras-p** [comment]
I just tested on Mac, and "it works". Some MonoDevelop version I had did not understand the "Tools version" of 15.0 in the project files, but Rider (2017.2) worked fine. Popped up some warnings about missing targets or somesuch, but actual build of Release|AnyCPU config did build into the proper location, and the test scenes worked fine.

**Comment by atteneder** [comment]
Not having a Rider license, I opened GLTFSerialization/GLTFSerialization/GLTFSerialization.csproj with a text editor and changed the ToolsVersion from 14.0 to 4.0:
`...<Project ToolsVersion="4.0"...`
After that I could open and compile with MonoDevelop as well (the one bundled with Unity 2017.2.0f3). Of course the UWP versions won't work.

**Comment by atteneder** [comment]
Visual Studio Community also seems to work (comes with newer Unity versions).
