### ISSUE TITLE
texCoord fields not respected

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/UnityGLTF#93]
The Unity Standard shader doesn't support selecting which UV channel to use for the albedo texture, and as a result the glTF `texCoord` fields are mostly ignored. This needs to change.

**Comment by sonygod** [comment]
because  your write dead code on that .

![image](https://user-images.githubusercontent.com/748320/55668177-8ddf3680-5898-11e9-9bc6-db7f2db95ed8.png)

![image](https://user-images.githubusercontent.com/748320/55668179-99326200-5898-11e9-9918-7f22409d475b.png)

![image](https://user-images.githubusercontent.com/748320/55668192-deef2a80-5898-11e9-85d5-bedae4805431.png)

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
